import json
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

try:
    bosto_DBFS = DBFSConnector.fetch([], {}, "5e9a8113ac8b1730f0805690", spark,
                                     "{'url': '/Demo/BostonTrain.csv', 'file_type': 'Delimeted', 'delimiter': ',', 'is_header': 'Use Header Line'}")

    bosto_AutoFE = TransformationMain.run(["5e9a8113ac8b1730f0805690"], {"5e9a8113ac8b1730f0805690": bosto_DBFS}, "5e9a8113ac8b1730f0805691", spark, json.dumps({"FE": [{"transformationsData": {}, "feature": "CRIM", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "3.95", "stddev": "10.87", "min": "0.01301", "max": "88.9762", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "ZN", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "9.73", "stddev": "19.58", "min": "0.0", "max": "100.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "INDUS", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "10.34", "stddev": "6.41", "min": "1.25", "max": "27.74", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "CHAS", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "0.06", "stddev": "0.24", "min": "0.0", "max": "1.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "NOX", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "0.56", "stddev": "0.12", "min": "0.392", "max": "0.871", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "RM", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "6.29", "stddev": "0.7", "min": "4.652", "max": "8.725", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "AGE", "type": "real", "selected": "True", "replaceby": "mean", "stats": {
                                          "count": "100", "mean": "69.95", "stddev": "26.75", "min": "6.5", "max": "100.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "DIS", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "3.88", "stddev": "2.13", "min": "1.358", "max": "9.2203", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "RAD", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "8.87", "stddev": "8.23", "min": "1.0", "max": "24.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "TAX", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "396.39", "stddev": "159.38", "min": "188.0", "max": "711.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "PTRATIO", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "18.16", "stddev": "2.1", "min": "13.0", "max": "21.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "B", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "349.63", "stddev": "102.21", "min": "0.32", "max": "396.9", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "LSTAT", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "12.89", "stddev": "6.88", "min": "2.87", "max": "31.99", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "MEDV", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "100", "mean": "21.71", "stddev": "9.09", "min": "7.4", "max": "50.0", "missing": "0"}, "transformation": ""}]}))

    functionRegression(bosto_AutoFE, ["CRIM", "ZN", "INDUS", "CHAS", "NOX",
                                      "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT"], "MEDV")

except Exception as ex:
    print(ex)
